image:
  file: gitpod.Dockerfile
tasks:
  - name: tailscaled
    command: |
      if [ -n "${TS_STATE_TAILSCALE_EXAMPLE}" ]; then
        # restore the tailscale state from gitpod user's env vars
        sudo mkdir -p /var/lib/tailscale
        echo "${TS_STATE_TAILSCALE_EXAMPLE}" | sudo tee /var/lib/tailscale/tailscaled.state > /dev/null
      fi
      sudo tailscaled
  - name: tailscale
    command: |
      if [ -n "${TS_STATE_TAILSCALE_EXAMPLE}" ]; then
        sudo -E tailscale up
      else
        sudo -E tailscale up --hostname "gitpod-${GITPOD_GIT_USER_NAME// /-}-$(echo ${GITPOD_WORKSPACE_CONTEXT} | jq -r .repository.name)"
        # store the tailscale state into gitpod user
        gp env TS_STATE_TAILSCALE_EXAMPLE="$(sudo cat /var/lib/tailscale/tailscaled.state)"
      fi
  - name: application
    command: |
      ./docker-start-containers.sh
      mvn install -DskipTests=false
      java -jar "./target/poc-dropwizard-docker-0.0.1-SNAPSHOT.jar" db migrate configuration.yml
