tasks:
  - init: |
      ./docker-start-containers.sh
      mvn install -DskipTests=false
    command: java -jar "./target/poc-dropwizard-docker-0.0.1-SNAPSHOT.jar" db migrate configuration.yml

ports:
  - name: db
    port: 5432
    visibility: public
