version: '2.1'
services:

  postgres:
    image: "postgres:11.2-alpine"
    environment:
      - POSTGRES_USER=poc_dbuser
      - POSTGRES_DB=poc
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 30s
      retries: 5
